org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

kotlin.code.style=official

# Único platform instalado é o android-36.1; AGP 8.7 oficialmente suporta até 35.
android.suppressUnsupportedCompileSdk=36
